// Mocks generated by Mockito 5.4.4 from annotations
// in easywrt/test/mcp_server_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i5;

import 'package:easywrt/model/device_profile.dart' as _i3;
import 'package:easywrt/provider/device_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DeviceProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceProvider extends _i1.Mock implements _i2.DeviceProvider {
  MockDeviceProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.DeviceProfile> get devices => (super.noSuchMethod(
        Invocation.getter(#devices),
        returnValue: <_i3.DeviceProfile>[],
      ) as List<_i3.DeviceProfile>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setActiveDevice(_i3.DeviceProfile? device) => super.noSuchMethod(
        Invocation.method(
          #setActiveDevice,
          [device],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadDevices() => super.noSuchMethod(
        Invocation.method(
          #loadDevices,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String addDevice({
    required String? name,
    required String? luciUsername,
    required String? luciPassword,
    required String? luciBaseURL,
    required String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDevice,
          [],
          {
            #name: name,
            #luciUsername: luciUsername,
            #luciPassword: luciPassword,
            #luciBaseURL: luciBaseURL,
            #token: token,
          },
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #addDevice,
            [],
            {
              #name: name,
              #luciUsername: luciUsername,
              #luciPassword: luciPassword,
              #luciBaseURL: luciBaseURL,
              #token: token,
            },
          ),
        ),
      ) as String);

  @override
  void editDevice(_i3.DeviceProfile? device) => super.noSuchMethod(
        Invocation.method(
          #editDevice,
          [device],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteDevice(String? uuid) => super.noSuchMethod(
        Invocation.method(
          #deleteDevice,
          [uuid],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
