include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    always_declare_return_types: true
    prefer_final_locals: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    avoid_void_async: true
    unawaited_futures: true