name: easywrt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: any
  go_router: any
  http: any
  logger: any
  path_provider: any
  synchronized: any
  path: any
  hive: any
  hive_flutter: any
  uuid: any
  mobx: any
  provider: any
  flutter_modular: any
  tray_manager: any
  window_manager: any
  dynamic_color: any
  screen_pixel: any
  local_auth: any
  shelf: any
  shelf_router: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  hive_generator: any
  build_runner: any
  source_gen: any
  mobx_codegen: any
  mockito: any

flutter:
  uses-material-design: true